#!/usr/bin/env python

import argparse
import mercurial.commands
import os
import os.path
import subprocess

from dulwich.repo import Repo
from mercurial import hg, ui as uimod
from os.path import dirname, basename, abspath, join
from sys import stderr

def slurp(filepath):
    with open(filepath, 'r') as f:
        return f.read()

def get_current_branch(repo_path='.'):
    return slurp(join(repo_path, '.git', 'HEAD')).split('/')[-1].strip()

def get_support_dir():
    return join(dirname(abspath(__file__)), 'tl-support')

def fast_import(hg_dir, git_dir='.'):
    exe_path = join(get_support_dir(), 'fast-export', 'hg-fast-export.sh')
    cmdset = 'cd %s && %s -r %s' % (
        abspath(git_dir),
        abspath(exe_path),
        abspath(hg_dir),
    )
    subprocess.call(cmdset, shell=True)

def cmd_clone(src, dst=None):
    '''
    Clones the given mercurial repository.
    '''
    if not dst:
        dst = basename(src)
    if os.path.exists(dst):
        stderr.write('fatal: destination "%s" exists.\n' % (dst,))
        return 1

    git_repo = Repo.init(dst, mkdir=True)
    os.chdir(dst)

    git_remote_dir = join('.git', 'hg-remote')
    os.mkdir(git_remote_dir)
    git_remote = Repo.init_bare(git_remote_dir)

    ui = uimod.ui()
    hg_dst = abspath(join('.git', 'hg-pure'))
    hg.clone(
        ui,
        {}, # peeropts
        source=src,
        dest=hg_dst,
        update=False
    )

    fast_import(hg_dst, git_remote.path)
    subprocess.call('''
        git remote add hg .git/hg-remote &&
        git config hg.tracking.master master &&
        git config branch.master.remote hg &&
        git fetch &&
        git branch --set-upstream master hg/master &&
        git pull &&
        git reset --hard
    ''',
                    shell=True)

def cmd_fetch(*args):
    ui = uimod.ui()
    pure_dir = join('.git', 'hg-pure')
    pure_repo = hg.repository(ui, path=pure_dir)
    # FIXME: use the api...
    subprocess.call('cd %s && hg pull' % pure_dir, shell=True)
    fast_import(pure_dir)

def cmd_push(*args):
    curr_branch = get_current_branch()
    if curr_branch == 'master':
        curr_branch = 'default'
    git_repo = Repo('.')

COMMANDS = {k[4:]: v for k, v in globals().iteritems() if k.startswith('cmd_')}

def main():
    p = argparse.ArgumentParser(
        usage='git tl [-h] <command> [<args>]',
        description='A git interface to mercurial.  hg++.',
    )

    p.add_argument('cmd', nargs='+', help='<%s>' % ('|'.join(COMMANDS)))
    args = p.parse_args()

    cmd_name, cmd_args = args.cmd[0], args.cmd[1:]
    if cmd_name not in COMMANDS:
        p.print_usage()
        return 1

    cmd = COMMANDS[cmd_name]
    try:
        return cmd(*cmd_args)
    except TypeError, e:
        # print the error, but not the traceback
        stderr.write('fatal: %s\n' % (e,))
        return 1

if __name__ == '__main__':
    exit(main())
